#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SplitView;
                ref class FontIcon;
                ref class TextBlock;
                ref class ToggleSwitch;
                ref class MediaElement;
            }
        }
    }
}

namespace MediaPlayerCPP
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SplitView^ Splitter;
        private: ::Windows::UI::Xaml::Controls::FontIcon^ Hamburger;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Header;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ toggleSwitchAudioDecode;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ toggleSwitchVideoDecode;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ mediaElement;
    };
}

